name: foodie
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-87.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  dots_indicator: ^2.1.0
  font_awesome_flutter: ^10.1.0
  sliding_up_panel: ^2.0.0+1
  get: ^4.6.5
  
  provider: ^6.0.3
  
  neopop: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/

  
  uses-material-design: true

 
  
  fonts:
    - family: SourceSerifPro
      fonts:
        - asset: assets/SourceSerifPro-Light.ttf
        
         
    - family: youngserif
      fonts:
        - asset: assets/youngserif-regular.otf

    - family: Mustica
      fonts:
        - asset: assets/Mustica-Pro.otf
    
    - family: Momcakelight
      fonts:
        - asset: assets/MomcakePro-Regular.ttf
        
    
    - family: Momcakemedium
      fonts:
        - asset: assets/MomcakePro-Medium.ttf